parameters:
#search services
    ow_ezfetchandlist.search_helper.ezfindlegacy.class: Ow\Bundle\OwEzFetchAndListBundle\Driver\SearchEzFindLegacyHelper
    ow_ezfetchandlist.search_helper.ezsymfony.class: Ow\Bundle\OwEzFetchAndListBundle\Driver\SearchEzSymfonyHelper

services:
#search services
    ow_ezfetchandlist.search_ezfindlegacy_helper:
        class: %ow_ezfetchandlist.search_helper.ezfindlegacy.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    ow_ezfetchandlist.search_ezsymfony_helper:
        class: %ow_ezfetchandlist.search_helper.ezsymfony.class%
        calls:
            - [ setContainer,[ @service_container ] ]